### ISSUE TITLE
couple meals

### ISSUE THREAD

**Issue by finger-prints** [weeniehut-jr/mealmenu#25]
**quesadillas & rice**
- [ ] tortilla
- [ ] chicken
- [ ] rice
- [ ] mixed cheese
- [ ] sour cream

**breakfast**
- [ ] bacon
- [ ] eggs
- [ ] white sugar
- [ ] ground sausage

**turkey burgies**
- [ ] ground turkey/patties
- [ ] bread
- [ ] ketchup
- [ ] (optional) lettuce
- [ ] (optional) tomato
- [ ] (optional) onion
- [ ] (optional) mustard

**curry**
- [ ] chicken breast
- [ ] flour
- [ ] panko
- [ ] egg
- [ ] pickle juice
- [ ] milk
- [ ] curry
- [ ] potato
- [ ] carrot
- [ ] onion
- [ ] garlic
- [ ] rice

**Comment by finger-prints** [comment]
this trip:

**quesadillas & rice**
- [ ] tortilla
- [ ] chicken
- [ ] rice
- [ ] mixed cheese
- [ ] sour cream

**breakfast**
- [ ] bacon
- [ ] eggs
- [ ] white sugar
- [ ] ground sausage

**snacks**
- [ ] apples
- [ ] mango
- [ ] watermelon
- [ ] cantaloupe
- [ ] pears

**Comment by finger-prints** [comment]
### Produce
- [x] apples
- [ ] mango
- [ ] watermelon
- [ ] cantaloupe
- [x] pears

### Meat
- [x] chicken
- [x] bacon
- [x] ground sausage

### Dairy
- [x] mixed cheese
- [x] sour cream
- [x] eggs

### Grains
- [x] tortilla
- [x] rice

### Pantry
- [x] white sugar

**Comment by michael-cox** [comment]
did a meal and abandoned... closing
